#!/bin/bash
shopt -s globstar

for num in {1..100}

do
       dir=/home2/danr/marxan_mammals/sp_25cap_10pc/run_$num
  inputdir=/home2/danr/marxan_mammals/input_100/run_$num

  timestamp=$(date +%F_%T)

  echo $dir

  filename=input_25pc.dat
  file=$dir/$filename

  rm $file

  echo "Input file for Annealing program.

This file generated by Inedit.exe.
written by Ian Ball and Hugh Possingham.
iball@maths.adelaide.edu.au
hpossing@maths.adelaide.edu.au

This particular file generated by Dan Rosauer using a shell script on" $timestamp "

General Parameters
VERSION 0.1
BLM  1.00000000000000E+0000
PROP  2.00000000000000E-0001
RANDSEED -1
BESTSCORE -1.00000000000000E+0000
NUMREPS 10

Annealing Parameters
NUMITNS 1500000
STARTTEMP -1.00000000000000E+0000
COOLFAC  6.00000000000000E+0000
NUMTEMP 20000

Cost Threshold
COSTTHRESH  1.084000000000E+0003
THRESHPEN1  1.150000000000E+0002
THRESHPEN2  1.000000000000E+0000

Input Files
INPUTDIR" $inputdir >> $file
  echo "
SPECNAME           spec_sp_25pc_cap.dat 
PUNAME             pu.dat 
PUVSPRNAME         puvspr2.dat 
MATRIXSPORDERNAME  sporder.dat

Save Files
SCENNAME output
SAVERUN 2
SAVEBEST 2
SAVESUMMARY 2
SAVESCEN 2
SAVETARGMET 2
SAVESUMSOLN 2
SAVELOG 2
SAVESNAPSTEPS 0
SAVESNAPCHANGES 0
SAVESNAPFREQUENCY 0
OUTPUTDIR ./

Program control.
RUNMODE 2
MISSLEVEL  9.50000000000000E-0001
ITIMPTYPE 3
HEURTYPE  1
CLUMPTYPE 0
VERBOSITY 2
" >> $file

done
