
library(RMySQL)
library(stringr)

moritz_db_login <- function(user, passwd) {

  # check for an existing connection with the same name
  if (exists("con")) {
    if (class(con) == "MySQLConnection") {
      dbDisconnect(con)
    }
    rm(con)
  }

  con <- dbConnect(RMySQL::MySQL(), dbname="moritz_specimen", host = "moritzdb-moritzlab.azva.dotcloud.net", port=2600, user=user, password=passwd)

  # check that the connection was successful
  success=F
  if (exists("con")) {
    if (class(con) == "MySQLConnection") { success=T }
  }

  if (success) {
    cat("\nConnected to moritz_specimen")
    return(con)
  } else {
    cat("\nConnection to moritz_specimen failed")
    return(0)
  }
}

com_sep <- function(vec, separator = ", ") {
  # this function takes each item in a vector and returns a single charater string in
  # which each item is separated by the separator, eg a comma
  result <- ""
  n <- length(vec)
  for (i in 1:n) {
    item <- vec[i]
    if (i < n) {
      result <- paste(result, item, separator, sep="")
    } else {
      result <- paste(result, item, sep="")
    }
  }

  result <- str_trim(result)
  return(result)
}

value_list_sql <- function(data, column_info, matching_field = NULL) {
  # takes a data frame with a single row, for the data to be updated in the database
  # the column names must match the corresponding database columns
  # column_info is generated by dbColumnInfo, and is used to identify the data types, to
  # get quoting right

  # returns a text string in the format required for an UPDATE statement, eg:
  # name = "gouldii", svl = 7, is_observation = 0

  col_count <- ncol(data)

  result <- ""
  for (i in 1:col_count) {
    col_name <- names(data)[i]

    # ignore the matching field if specified
    if (col_name == matching_field) {next}

    col_class <- as.character(column_info[which(column_info$name==col_name), "Sclass"])

    if (col_class=="character") {
      result <- paste(result, names(data)[i], ' = "', data[i], '"', sep="")
    } else { # assumes other column classes are unquoted
      result <- paste(result, names(data)[i], " = ", data[i], sep="")
    }

    if (i < col_count) {result <- paste(result, ", ", sep="") }
  }

  return(result)
}
